apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - ../../base

patches:
  # Prod: STRICT mTLS enforced
  - target:
      kind: PeerAuthentication
      name: default
    patch: |
      - op: replace
        path: /spec/mtls/mode
        value: STRICT

  # Prod: 1% tracing sampling, REGISTRY_ONLY egress
  - target:
      kind: IstioOperator
      name: istio-control-plane
    patch: |
      - op: replace
        path: /spec/meshConfig/defaultConfig/tracing/sampling
        value: 1.0
      - op: replace
        path: /spec/meshConfig/outboundTrafficPolicy/mode
        value: REGISTRY_ONLY
      - op: replace
        path: /spec/components/pilot/k8s/hpaSpec/minReplicas
        value: 3
      - op: replace
        path: /spec/components/ingressGateways/0/k8s/hpaSpec/minReplicas
        value: 3

commonLabels:
  environment: prod
