apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-api

labels:
  - pairs:
      app.kubernetes.io/name: python-api-base
      app.kubernetes.io/component: eventing
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - kafka-source.yaml
  - broker.yaml
  - trigger.yaml
