apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kepler-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: kepler
  app.kubernetes.io/component: energy-monitoring
  app.kubernetes.io/part-of: greenops
