apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-api

labels:
  - pairs:
      app.kubernetes.io/name: python-api-base
      app.kubernetes.io/component: api
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

resources:
  - service.yaml
  - configmap.yaml
  - serviceaccount.yaml
