global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dapr'
    static_configs:
      - targets: ['python-api-dapr:9090']
    metrics_path: /metrics

  - job_name: 'python-api'
    static_configs:
      - targets: ['python-api:8000']
    metrics_path: /metrics
