apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-api-dev

namePrefix: dev-

labels:
  - pairs:
      environment: development
    includeSelectors: false

resources:
  - ../../base

patches:
  - path: patches/service-patch.yaml
  - path: patches/configmap-patch.yaml
