apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.2/manifests/install.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: argocd

patches:
  - path: argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-rbac-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
