apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - ../../base

patches:
  # Staging: STRICT mTLS (production-like)
  - target:
      kind: PeerAuthentication
      name: default
    patch: |
      - op: replace
        path: /spec/mtls/mode
        value: STRICT

  # Staging: 5% tracing sampling
  - target:
      kind: IstioOperator
      name: istio-control-plane
    patch: |
      - op: replace
        path: /spec/meshConfig/defaultConfig/tracing/sampling
        value: 5.0

commonLabels:
  environment: staging
