apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - namespace.yaml
  - istio-operator.yaml
  - gateway.yaml
  - virtualservice.yaml
  - destinationrule.yaml
  - peerauthentication.yaml
  - authorizationpolicy.yaml
  - requestauthentication.yaml
  - serviceentry.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: python-api-base
